### get api 
GET http://localhost:5000
 

### get all task from the server
GET http://localhost:5000/api/v1/

### post api 
POST  http://localhost:5000/api/v1
Content-Type: application/json

{
"task": "learning to code",
"hr": 15
}


### patch api 
PATCH  http://localhost:5000/api/v1
Content-Type: application/json

{
"_id": "6062a2e2aca4f12ba015b7ec",
"todo": true
}

 
### Put api 
PUT  http://localhost:5000/api/v1
Content-Type: application/json

{
"task": "learning to code",
"hr": 16
}

### delete api 
DELETE  http://localhost:5000/api/v1
Content-Type: application/json

{
ids: []
}